package pttest2;

public enum AgeRange {
	SEVENTEEN_TO_TWENTYONE,
	TWENTYTWO_TO_TWENTYSIX,
	TWENTYSEVEN_TO_THIRTYONE,
	THIRTYTWO_TO_THIRTYSIX,
	THIRTYSEVEN_TO_FORTYONE,
	FORTYTWO_TO_FORTYSIX,
	FORTYSEVEN_TO_FIFTYONE,
	FIFTYTWO_TO_FIFTYSIX,
	FIFTYSEVEN_TO_SIXTYONE,
	SIXTYTWO_AND_HIGHER
}
